services:
  - type: web
    name: ukraine-weather-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /health